apiVersion: fabricator.cestus.io/v1alpha1
kind: Config
components:
  - name: "fabricator-generate-project-go"
    generator: fabricator-generate-project-go
    spec:
      goModule: code.cestus.io/tools/fabricator-generate-project-go
      repoURL: https://gitlab.com/cestus/fabricator/fabricator-generate-project-go
      isTool: true
  - name: "fabricator-generate-project-go"
    generator: fabricator-generate-plugin-go
    spec:
      pluginName: fabricator-generate-project-go
      isGenerationPlugin: true
